### ISSUE TITLE
Fatal error: Class 'Share_Album_maintain' not found

### ISSUE THREAD

**Issue by Amgine0** [petitssuisses/piwigo-ShareAlbum#22]
Fatal error: Uncaught Error: Class 'Share_Album_maintain' not found in /path/admin/include/plugins.class.php:96 Stack trace: #0 /path/admin/include/plugins.class.php(128): plugins::build_maintain_class('Share_Album') #1 /path/admin/plugins_installed.php(73): plugins->perform_action('activate', 'Share_Album') #2 /path/admin/plugins.php(46): include('/raid/www/photo...') #3 /path/admin.php(311): include('/raid/www/photo...') #4 {main} thrown in /path/admin/include/plugins.class.php on line 96

**Comment by petitssuisses** [comment]
Hi, 
from an update or an install ?

**Comment by Amgine0** [comment]
Install, almost-new piwigo instance.

The plugin also cannot be deleted from the control panel.

**Comment by petitssuisses** [comment]
Ok, i'll fix. Delete the plugins/sharealbum folder in the meantime

**Comment by petitssuisses** [comment]
Thanks for reporting ! ^^

**Comment by Amgine0** [comment]
You are welcome!

**Comment by petitssuisses** [comment]
Fixed ! Was not due to the code, but the configuration of the export within Piwigo extension interface. I may have changed the settings of the git export. Thanks again for reporting

**Comment by Amgine0** [comment]
Note: Re-installed. It currently states "WARNING! this plugin does not seem to be compatible with this version of piwigo."

When activated anyway:
<pre lang=bash>
Fatal error: Uncaught Error: Class 'Share_Album_maintain' not found in /raid/www/photonegs/admin/include/plugins.class.php:96 Stack trace: 
#0 /raid/www/photonegs/admin/include/plugins.class.php(128): plugins::build_maintain_class('Share_Album') 
#1 /raid/www/photonegs/admin/plugins_installed.php(73): plugins->perform_action('activate', 'Share_Album') 
#2 /raid/www/photonegs/admin/plugins.php(46): include('/raid/www/photo...') 
#3 /raid/www/photonegs/admin.php(311): include('/raid/www/photo...') 
#4 {main} thrown in /raid/www/photonegs/admin/include/plugins.class.php on line 96
</pre>

**Comment by petitssuisses** [comment]
Did you update it to 1.2.1 before installing again?

**Comment by Amgine0** [comment]
Possibly not; I used the release via the control panel. Will download from git and test again.

**Comment by petitssuisses** [comment]
You can do an update from the administration panel : Plugins > Manage > Check for update, or if you deleted the plugin, install the newest version

**Comment by Amgine0** [comment]
Yes, the new version installed via the administration panel, and it appears to be working.

This shows another issue about localization, however. I will open a new issue.
