### ISSUE TITLE
Hacking attempt when accessing URL

### ISSUE THREAD

**Issue by Cr0sby** [petitssuisses/piwigo-ShareAlbum#24]
I receive a blank page with the message "Hacking attempt" when I attempt to access the URL generated for an album.

I have tried regenerating the URL and it gives the same error.

I am using the latest version of the plugin 1.2.1 on the latest version of Piwigo

**Comment by petitssuisses** [comment]
Hi, thanks for the feedback. 
May I know what is the original structure of the album you're trying to reach ? (is it a sub-album ?)
Is it the case for any of the links you're trying to share ? (as an example, if you share an album which is at root directory)

**Comment by Cr0sby** [comment]
Hi, I have discovered that I have this problem if the album I am sharing is empty (e.g. if I share a main folder where all the photos are in the sub-folders) If I add a photo then the link works and I can then see the folder and that added photo.
Therefore I believe my main issue may be that I am trying to share sub-folders and the generated user does not have access to the parent main folder?
My use case is:
/holidays
/holidays/2017 (shared but receive the above error upon access)

**Comment by Cr0sby** [comment]
To confirm that with the latest version and my comment above, the error has changed since I opened the issue and it now says: You are not authorised to access the requested page.

**Comment by petitssuisses** [comment]
Please check at comments and correction of #40 as well.
