### ISSUE TITLE
Customise screen truncates email address

### ISSUE THREAD

**Issue by Cr0sby** [petitssuisses/piwigo-ShareAlbum#25]
When I go onto the photograph gallery customise screen, my email address is truncated - so it is showing only with the first part:

test@mail.com is shown only as test

I need to add back the full address, for example if I want to change the Theme.

This is due to an interaction between browser autocomplete and the name of the data entry field. I suggest to add autocomplete='off' to the field to prevent this.

**Comment by petitssuisses** [comment]
What is the theme you are using ?

**Comment by petitssuisses** [comment]
And another question, why are you thinking it is caused by the ShareAlbum plugin ?

**Comment by petitssuisses** [comment]
@Cr0sby could you please retest with latest version available ? I fixed css which might be the cause of the issue you faced in this #25

**Comment by Cr0sby** [comment]
Hi, This seems to be fixed now.
thanks.

**Comment by petitssuisses** [comment]
Great ! I’ll look into the other problem (I have the same, so I hope to find a solution soon)
