### ISSUE TITLE
1.2.1: Localization issue

### ISSUE THREAD

**Issue by Amgine0** [petitssuisses/piwigo-ShareAlbum#26]
Not-logged-in persons following the generated link only see the site localized to fr_FR. This is true even when a different localization is requested via the url. 

![piwigo screen grab showing url and localization](https://user-images.githubusercontent.com/1359795/33529484-5ae8ff50-d869-11e7-891e-22b0c26660a8.png)

**Comment by petitssuisses** [comment]
Nothing in the code forces localization, I do not think it is related to the extension but piwigo behaviour ? I close this one

**Comment by petitssuisses** [comment]
I think I found it, the localization of created user may be different as the site one. Will fix it with default language of the configuration

**Comment by petitssuisses** [comment]
Fixed. The created user for a specific share is now created with the Piwigo default locale. Warning, it case of change of the default locale, it will not apply to previously created shares / user
