### ISSUE TITLE
Error when I activate Share Album

### ISSUE THREAD

**Issue by Gmessyhome** [petitssuisses/piwigo-ShareAlbum#32]
Hi when i go to activate the Share Album extension i get this error 

Parse error: syntax error, unexpected '[' in /homepages/25/d65753354/htdocs/gmessyhome/gallery/plugins/ShareAlbum/maintain.class.php on line 119

Any solutions would be welcome

My Pwingo is up to date and running latest updates

**Comment by petitssuisses** [comment]
Hi Gmessyhome, do you still get the error ? Further updates should have solved your issues. Please inform so that I could close the issue if not the case anymore. Thanks !

**Comment by petitssuisses** [comment]
Should not be an issue anymore as no other error was reported. I'll close the case, please feel free to open it again or create a new one on purpose.
