### ISSUE TITLE
You are not authorised to access the requested page

### ISSUE THREAD

**Issue by drenghel** [petitssuisses/piwigo-ShareAlbum#40]
Hi, 
first and foremost, I looked-up #21 #24, looked like it was the same issue, but not so much convinced of it now.

I got this error ```You are not authorised to access the requested page```  (URL looks like this after resolving `http://MYSITE/SOMEFOLDER/piwigo/index.php?/category/5`  
when I try to test a shared link I created.  

Here's some specs :

    Piwigo 2.9.4  
    Operating system: Linux  
    PHP: 7.0.33-0+deb9u1 (Show info) [2019-01-03 01:23:33]  
    MySQL: 5.5.5-10.1.37-MariaDB-0+deb9u1 [2019-01-03 01:23:33]  
    Graphics Library: GD 2.2.4  
    Plugin version : Revision 1.2.2

I should say that I can reproduced this only with some photos ( Yeah I know, weird and not precise enough)  
Somehow it works with another album...  
Even tried to move the photos to that working album, and surprise, the photos would not show in it.

I'm pretty bummed out, I l'd like some help trying to figure out what's wrong ! :)  

Cheers, Drenghel

**Comment by Andre-Rb** [comment]
Figured it out, the property of my photos ` Who can see this photo? ` was set to admin only, which is to me _confusing_, because **I shared an album with a logging-less link, full of pics I couldn't see because i was **not logged as an Admin.****   

_IMHO_, getting such a vague error is too confusing, I would rather be able to see an empty album.  
Not sure it's in the scope of this repo.  

Anyway, I don't close the issue yet, in case it can be changed as 'improvement issue' but thanks for the work here !

**Comment by BenMak** [comment]
The error message is misleading and at least not helpful.
Showing an empty album would indeed help, pointing the user in the right direction and make him wonder why the album is opened but the pictures are not displayed.

When ShareAlbum registers a new sharealbum-user no value is assigned to the field 'Privacy Level', this remains empty. This can be verified when checking the Users List (Piwigo>Administration>Users>Manage>Users-list). Effectively the value is zero i.e. 'Everybody'.

Setting the (privacy) level of all images in the share-album to 0 (Everybody) would indeed display all images but this is no option to me. The setting of (different) privacy levels of the images is done for a reason, I don't necessarily want all images in an album to be visible to just everybody.

The route for me to follow is to edit the new sharealbum-user record in Piwigo>Administration>Users>Manage>Users list and set the privacy level equal to that of the images I want to share.

To automate the process, I added a hack to the script in ../plugins/ShareAlbum/main.inc.php after line 188.
Effectively the privacy level of the sharealbum-user is set equal to the lowest image privacy level found in the share album. 

```
180     // Register user
181     $new_user_id = sharealbum_register_user($sharealbum_new_user,sharealbum_generate_code(SHAREALBUM_USER_PASSWORD_LENGTH, false,true));
182     if (sharealbum_grant_private_category($new_user_id,$sharealbum_cat)) {
183          // TODO handle insertion error
184          // Insert code into sharealbum table
185           pwg_query("
186                      INSERT INTO `".SHAREALBUM_TABLE."` (`cat`,`user_id`,`code`,`creation_date`)
187                      VALUES (".$sharealbum_cat.",".$new_user_id.",'".$new_code."','".date("Y-m-d H:i:s")."')
188                     ");
189
190 // HACK privacy level
191     // Set user privacy level to lowest level of images in share album
192     // Get minimum privacy level
193     $result = pwg_query("
194                          SELECT MIN(`level`) AS min_level
195                          FROM `pi_images`
196                          WHERE `storage_category_id` = '".$sharealbum_cat."'
197                         ");
198
199     if (pwg_db_num_rows($result))
200         {
201          $row = pwg_db_fetch_assoc($result);
202          $privacy_level = $row[ 'min_level'];
203         }
204
205     // Set user level in USER_INFOS_TABLE
206     pwg_query("
207                UPDATE `".USER_INFOS_TABLE."`
208                SET `level` = ".$privacy_level."
209                WHERE `user_id` = ".$new_user_id.";
210               ");
211 //END HACK privacy level
212
213     redirect(PHPWG_ROOT_PATH.'index.php?/category/'.$sharealbum_cat.'&'.SHAREALBUM_URL_MESSAGE.'='.SHAREALBUM_URL_MESSAGE_SHARED);
214  }
215  break;
```

**Comment by petitssuisses** [comment]
Hi, many thanks ! very interesting situation (i did not face it myself). I include your code in the main branch (and thanks again)
