### ISSUE TITLE
Can't find Share Button. 

### ISSUE THREAD

**Issue by navaraga** [petitssuisses/piwigo-ShareAlbum#42]
I installed the Share Album plugin.
I created an album, made it private and uploaded a photo.
I can't find the Share Button. 
In Albums -> Manage (on left sidebar), when I hover on album name, I don't see Share Button in the commands that show below that. Nor do they show up when I select the album.
is it possible to add a screenshot to show where this button should show up, to the documentation? or describe it? thanks

**Comment by petitssuisses** [comment]
Hi,
You need to go into the album to see the Share menu.
Example attached
Hope this helps !

![sample](https://user-images.githubusercontent.com/10274731/64906404-8729da80-d6e6-11e9-977b-a2b582743ce9.png)

**Comment by regexgit** [comment]
I also searched for a very long time in the admin part, which seems more logical, and we must not be the only ones, I suggest adding this information in "description / usage"

**Comment by navaraga** [comment]
Hi Arnaud,

Thanks for including the screenshot, but I don’t know how to get to that page.
I’m running the latest PiWiGo.

Do you mind clarifying the steps?

Here is what I did:

1) Logged into my site and Clicked on Administration
2) In the left sidebar, I clicked on Albums, and tried both Manage and Properties.
Properties shows Public and Private albums.
Share is supposed to work for Private Albums right?
3) I clicked on one of the private albums
4) I don’t see Share icon anywhere..
5) I clicked on “Edit”   I still don’t see Share icon/button

Thanks,
Raja

Here are some screenshots:

**Comment by regexgit** [comment]
Do not click on Administration !!!
As the screenshot shows you have to go to the album, the "normal view"

**Comment by navaraga** [comment]
Thanks for the quick response.. I couldn’t find the share link/button in the normal view either. 

Here are the screen shots:

**Comment by regexgit** [comment]
I'm afraid I can't help you anymore, on my system I only see 2 cases where the share icon is invisible:
1. public album
2. album containing other albums (only one "leaf" album can be shared)

By the way, I don't see your screenshots (but I see the first of petitssuisses so I think you made a mistake). Here is one with the icon:
![pwg_share](https://user-images.githubusercontent.com/37620014/65261590-e7ff4b80-db08-11e9-86e5-f6b2bd821ed7.JPG)

**Comment by navaraga** [comment]
I added the screenshots to the email reply. May be they didn’t show up on GitHub.

Either way this is frustrating.

I can’t even find “Jump To Album” for private albums, so I can’t get to the screenshot you shared, where I can navigate photos in the private album. I can get to it for public albums, but as the docs say and as you noted, Share is not available for that mode.

Not sure if it is my mistake or a bug in the software.

**Comment by regexgit** [comment]
Last thing: are you sure you have set the right permissions on private albums ? otherwise even if you are webmaster you do not see them in gallery.

**Comment by navaraga** [comment]
You nailed it. 

As soon as I addd myself to the Private Album, “Jump to album” appeared and was able to see the Share icon and create the link.

Thank you very much for figuring this out and suggesting it!!

Raja

**Comment by rendaw** [comment]
Would you please add the photo to the readme?  I spent about an hour trying to find the link (TBH I don't have a share button for some reason) and this would have helped me save a lot of time.

Also it might help to mention that this should be when _viewing_ the album, not the album administration page.

**Comment by petitssuisses** [comment]
Yes, I will. Btw, I found a reason, which will be fixed during the lockdown period (COVID-19) ;) Which theme are you using ?

**Comment by regexgit** [comment]
Thanks to covid-19 all my pending requests will be corrected, good news ! ;)

**Comment by HypKin** [comment]
just installed piwigo, cant find the share button either. have admin rights, added my admin user to the private album... using the current version with the default theme.

**Comment by emmanuelmathot** [comment]
Indeed, there seems to be an issue with the CSS. The function is here but the button is hidden.
![Screenshot_20200428_120557_1](https://user-images.githubusercontent.com/1178857/80475621-69457900-8949-11ea-91d4-9aff3565b50a.png)
![Screenshot_20200428_120557_2](https://user-images.githubusercontent.com/1178857/80475627-6cd90000-8949-11ea-87eb-26c328439e6d.png)

**Comment by petitssuisses** [comment]
Modus should be fixed with version 1.4. 
'll add a comment on the admin pages as well to ensure that users of the plugin really understand it is intended to work for Private Albums. @regexgit, your issues are fixed but, during 2nd lockdown COVID-19 phase !
