### ISSUE TITLE
Recursive share

### ISSUE THREAD

**Issue by regexgit** [petitssuisses/piwigo-ShareAlbum#43]
Sharing only applies to one album and not to his descendants, which does not help me because I often cut my albums into sub-albums, for example 'trip/day1', 'trip/day2',..etc.

In this case we will never see the sub-albums 'day1', 'day2, ... (1) in the shared album 'trip' (and it is out of the question to share each sub-album one by one).

Would it be possible to add a "recursive" option?

(1) worst: with the parent album empty we got a message "not authorized" ("Vous n'êtes pas autorisé à accéder à la page demandée") with login link.

**Comment by tijmen61** [comment]
Is there any update on this matter?

**Comment by petitssuisses** [comment]
Hi, sorry for the long delay replying to your request. No, it will not be possible, the purpose of the module is to share one album only. 
But there may be a "trick", maybe you can try and test it : for any shared album, a specific user is created (pattern by default is share_xxxxxxxx). You can give rights for this user for any sub-album using Piwigo permissions screen.

**Comment by regexgit** [comment]
Yes, that could be an acceptable workaround without this problem: once in the sub-album it is impossible to go up to the next level.
For example, either a shared link to "mytrip": by clicking on  "/root/ mytrip/day1"  what is displayed in the breadcrumb is "/root/day1", we have lost "mytrip" (tested in elegant and modus themes).
The only way to come back to "mytrip" is to reuse the shared link, not very user-friendly.

**Comment by petitssuisses** [comment]
@regexgit , the breadcrumbs management have been fixed in latest Github commit (not yet released, but next release will correct the behaviour). You will be able to navigate in the sub albums / root album of the share
