### ISSUE TITLE
Share album plugin error

### ISSUE THREAD

**Issue by lyndseylola** [petitssuisses/piwigo-ShareAlbum#48]
New to Piwigo - all I want to do is create galleries for my photos and most importantly send links to clients to view.

Spent the last few hours trying to get the Share Album plugin to work ... I get the following error:

Parse error: syntax error, unexpected '[' in /home/sites/lyndseychallis.com/public_html/photos/plugins/ShareAlbum/maintain.class.php on line 122

I've seen a previous post with something similar that was never answered and supposedly should have been solved with newer releases (which is obvs what I'm installing although have tried manually uploading an older version too.)

Would appreciate help on what's going wrong as pulling my hair out and ready to give up on Piwigo completely!

**Comment by petitssuisses** [comment]
May I ask you which PHP version you are running ?

**Comment by petitssuisses** [comment]
No feedback, closing this as not reproduced
