### ISSUE TITLE
After upgrade to 1.7 no private albums recognized

### ISSUE THREAD

**Issue by erAck** [petitssuisses/piwigo-ShareAlbum#51]
After an upgrade to 1.7 private albums are not offered on the admin's Share Album -> Shared Albums page under "Share a new album". The listbox has only one entry "No private album to be shared (or which is not yet shared)", which is not true.

**Comment by petitssuisses** [comment]
Hi. 
The albums which are listed here are the ones who contain pictures, which are private (vs public) and not already share. Are you sure : 
- they do contain photos
- they are private
- they are not already shared
?

**Comment by erAck** [comment]
All questions answered with Yes ;) 

MySQL: 8.0.17

Already this partly query from admin/albums.php returns a result set with only one private album from piwigo_categories:
```
SELECT c.*, count(i.id) as nb_images
  FROM piwigo_categories c, piwigo_images i
  WHERE status = 'private'
```
instead of the expected private categories (which
```
SELECT c.*
  FROM piwigo_categories c
  WHERE status = 'private'
```
does) plus images, and adding
```
  AND i.storage_category_id = c.id
  GROUP BY c.id
```
returns an empty result set; piwigo_sharealbum is empty.
The `count(i.id) as nb_images` in SELECT forces the result to one record.

Furthermore, .IMAGES_TABLE. storage_category_id is not NULL only for physical albums. The query can't even work for virtual albums.

Also, I think that attempting to create an exploded table (if I interpret the approach correctly) of private categories with all their assigned images just to group them by the category ids isn't such a good idea, if you take large databases in account.

**Comment by petitssuisses** [comment]
Hi,
Thanks for your complete reply ! I first tested only on physical albums (which is the case for my gallery). Query may be optimized (using an outer join) by so far, it runs smoothly for a 100'000+ images instance.
I changed the query to make use of the image_category table, which is much more appropriate as valid for both type of albums.

**Comment by erAck** [comment]
How comes Piwigo advertises a 1.8 update fixing this, this issue is closed, but all code is unchanged?
(btw, my nick is erAck, not ErAck ;-)

**Comment by petitssuisses** [comment]
1.9 is advertised, with pushed changes to Github (was committed locally only ;))
Please let me know if it fixes your private virtual albums availability in your albums that can be shared.
(btw, corrected your nick ;-)

**Comment by erAck** [comment]
Yes, 1.9 now works.
Thanks!

**Comment by petitssuisses** [comment]
Great !
