### ISSUE TITLE
1 of 3 albums won't show up in the picklist

### ISSUE THREAD

**Issue by freemann** [petitssuisses/piwigo-ShareAlbum#53]
Installed a clean docker instance of piwigo on :latest and  having problems with sharing albums.

I have 3 private albums, all with at least 1 picture in the album and 1 albums is not showing up in the picklist.

Have no idea what's going on, here some screenshots;
![Screenshot_20201210-142830](https://user-images.githubusercontent.com/601053/101778735-8bfd5a00-3af4-11eb-941b-9d57779d278b.jpg)
![Screenshot_20201210-142921](https://user-images.githubusercontent.com/601053/101778741-8d2e8700-3af4-11eb-9d36-84d755aa7100.jpg)
![Screenshot_20201210-150844](https://user-images.githubusercontent.com/601053/101782828-c74e5780-3af9-11eb-98e3-fa8cd96e6a21.jpg)

Here's the gallery which is not showing up in the picklist;
![Screenshot_20201210-145458](https://user-images.githubusercontent.com/601053/101781674-683c1300-3af8-11eb-93d9-e5173569bd4d.jpg)

**Comment by freemann** [comment]
Also when I can a share, it's not possible to reshare that album again. It also is not showing up in the picklist.

**Comment by petitssuisses** [comment]
Can you share your technical details (php version, database type and version, etc.)

**Comment by freemann** [comment]
Most recent piwigo docker tag, mysql 5.7(docker image), php -v of host os is:
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Comment by petitssuisses** [comment]
thanks. and can you post the results of the individual queries (hiding dirs if physical and name of the dir being relevant)

SELECT id,id_uppercat,dir,rank,status,site_id,visible,representative_picture_id,uppercats,commentable,global_rank,image_order FROM `piwigo_categories` where status='private' 

and

SELECT category_id,count(image_id) FROM `piwigo_image_category` GROUP BY category_id

**Comment by freemann** [comment]
It's a bit busy here and found some time to look into it;
```
mysql> SELECT category_id,count(image_id) FROM piwigo_vrienden_image_category GROUP BY category_id;
+-------------+-----------------+
| category_id | count(image_id) |
+-------------+-----------------+
|           1 |               3 |
|           2 |               3 |
+-------------+-----------------+
2 rows in set (0.00 sec)

mysql> SELECT id,id_uppercat,dir,rank,status,site_id,visible,representative_picture_id,uppercats,commentable,global_rank,image_order FROM piwigo_vrienden_categories where status='private'
    -> ;
+----+-------------+------+------+---------+---------+---------+---------------------------+-----------+-------------+-------------+-------------+
| id | id_uppercat | dir  | rank | status  | site_id | visible | representative_picture_id | uppercats | commentable | global_rank | image_order |
+----+-------------+------+------+---------+---------+---------+---------------------------+-----------+-------------+-------------+-------------+
|  1 |        NULL | NULL |    2 | private |    NULL | true    |                         1 | 1         | true        | 2           | NULL        |
|  2 |        NULL | NULL |    1 | private |    NULL | true    |                         4 | 2         | true        | 1           | NULL        |
+----+-------------+------+------+---------+---------+---------+---------------------------+-----------+-------------+-------------+-------------+
2 rows in set (0.00 sec)

```

**Comment by freemann** [comment]
Think I found something. 
I have now 2 albums;
- Aa
- Bb

When I add to both albums 3 totally different pics, the show up in the picklist.
When I add in both albums 1 picture with the same filename, the albums won't show up in the picklist.

Could this be, a part of the, problem?

**Comment by freemann** [comment]
please let me known if there's anything I can do to help fix this :)

**Comment by petitssuisses** [comment]
Hi, same as you, I had not enough free time until now. I'll let you know asap ;) thanks for the feedback

**Comment by freemann** [comment]
Looked into the code yesterday, but the database schema is unfamiliar for me and don't known what and why you do things in code you do. If you have a test version I'm glad to test it and please send me a howto add the new code/files to piwigo 😄

**Comment by freemann** [comment]
Changed the following line;
https://github.com/petitssuisses/piwigo-ShareAlbum/blob/master/admin/albums.php#L35
to:
```  AND i.image_id <> c.id```

It fixes the problem for me, but don't know what the effect are for others.

**Comment by petitssuisses** [comment]
Hi.
Here is the corrected sql query (list of albums not yet shared and which contain at list 1 picture) : 

SELECT ic.category_id as 'id', c.name, COUNT(ic.image_id) FROM piwigo_image_category ic, piwigo_categories c WHERE ic.category_id IN ( SELECT c.id FROM piwigo_categories c LEFT JOIN piwigo_sharealbum s ON c.id = s.cat WHERE s.cat IS NULL ) AND c.id = ic.category_id GROUP BY ic.category_id

**Comment by petitssuisses** [comment]
Please let me know @freemann if it works, I'll release a fix

**Comment by freemann** [comment]
Looks like its working great!! Thank you very much!!
