### ISSUE TITLE
HTTPS link on shared albums overview

### ISSUE THREAD

**Issue by freemann** [petitssuisses/piwigo-ShareAlbum#54]
I'm running my album on a domain with HTTPS and the links in de shared albums overview only show HTTP links.
Would be nice if https is recognized and automatically shown in the share albums overview.

![image](https://user-images.githubusercontent.com/601053/102690211-26038780-4204-11eb-8dd2-df2b127412de.png)

**Comment by petitssuisses** [comment]
Yes, is linked to a limitation of the get_absolute_root() piwigo function, will enhance it.

**Comment by petitssuisses** [comment]
If you install the plugin Force HTTPS (and activate it), do your link still show up with http:// ?

**Comment by freemann** [comment]
Looks like it's a issues with reverse proxies. Made a pull request on the piwigo codebase to hopefully fix this.

**Comment by tony53517230** [comment]
Hi, I have the same problem.
I am using nginx(use https) to reverse proxy piwigo(use http)
Is there a solution yet?

**Comment by tony53517230** [comment]
Hi, I found the solution at URL and it is indeed a reverse proxy issue.
Here are the details.
I am using nginx as a reverse proxy server, and I added the following to the config file:
`
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
`

Then I added the following to local/config/config.inc.php:
`
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https'){
       $_SERVER['HTTPS']='on';
}
`
It's work!!

**Comment by petitssuisses** [comment]
Thanks for the tip.
I'll add it to the README / FAQ
