### ISSUE TITLE
Can't find plugin in Piwigo

### ISSUE THREAD

**Issue by xplosionmind** [petitssuisses/piwigo-ShareAlbum#62]
Hello everybody, pardon me for the dumbness of the question; I am a Piwigo newbie and I'd like to have Flickr functionality of generating a unique album link which not logged users can have. I believe this is what this plugin provides. Nevertheless, I can't find it in the plugins list of the Piwigo backend interface (not self-hosted).

How could it be so?

Thanks a lot!

**Comment by petitssuisses** [comment]
Hi, are you on piwigo.com or do you self host your piwigo instance ?

**Comment by xplosionmind** [comment]
> Hi, are you on piwigo.com or do you self host your piwigo instance ?

I'm on piwigo.com. I figured I need to ask Piwigo to install the extension on my instance for me. I sent them an email a few days ago. Thanks a lot!
