### ISSUE TITLE
Piwigo 11 compatibility

### ISSUE THREAD

**Issue by tmkklivecom** [petitssuisses/piwigo-ShareAlbum#64]
Is plugin compatible with Piwigo 11?

**Comment by petitssuisses** [comment]
Hi, not yet. I was on a new release coding when Piwigo 11 went out. I'll update it soon so that it gets compatible.

**Comment by petitssuisses** [comment]
Hi @tmkklivecom , fixed now and released as a New version on piwigo ! Enjoy

**Comment by tmkklivecom** [comment]
thx
