### ISSUE TITLE
Add configuration to allow non-administrators to create share-urls

### ISSUE THREAD

**Issue by Nudin** [petitssuisses/piwigo-ShareAlbum#72]
I would like to give other users also the possibility to share albums. Would it be possible to add a configuration option that allows to set a user status (or alternatively a group) that should have the share icon and can use it to create share URLs?

**Comment by petitssuisses** [comment]
Hi. Yes, possible and makes sense if you trust enough one or several users. I'll add this to the next features

**Comment by petitssuisses** [comment]
Implemented
