### ISSUE TITLE
nested albums

### ISSUE THREAD

**Issue by bfd69** [petitssuisses/piwigo-ShareAlbum#73]
is it possible to add an option to include subalbums (sous albums) ?
i think it should be easily done because if i share an album and go on the security, i found that a user share_xx is created with access, and if i check apply on subalbums and save, my subalbums are accessible from the link share.

whats your opinion ?

**Comment by petitssuisses** [comment]
Hi. Yes, that's in the roadmap, and this will complete #43 as well.

**Comment by bfd69** [comment]
yessss trop fort
pleaaaase before the release add date and time limit for #43 
pls pls pls
share_album = plugin of the year

i tried the private_share plugin but pdfs and videos dont work, yours is the best :+1:

**Comment by petitssuisses** [comment]
Duplicate to #43, closing this one to the profit of the oldest one

**Comment by petitssuisses** [comment]
Implemented
