### ISSUE TITLE
Undefined index: option_recursive_shares

### ISSUE THREAD

**Issue by mattsches** [petitssuisses/piwigo-ShareAlbum#81]
Piwigo version: 11.5.0
Plugin version: 11.8
PHP: 7.4.18

When I am logged in as admin and I open a category page (e.g. `https://example.org/index.php?/category/2`), I get the following notice:
```
Notice: Undefined index: option_recursive_shares in /[…]/plugins/ShareAlbum/include/public_events.inc.php on line 72
```
Not a major issue, but still …

**Comment by mattsches** [comment]
So I went to the plugin configuration and re-saved all the configuration options again without changing anything, and now the notice seems to be gone.

A check for the array key could still be added, but feel free to close this issue anyway.

**Comment by petitssuisses** [comment]
Ok thanks for the update. 
I need to improve the upgrade procedure
