### ISSUE TITLE
Sharing an album runs into PHP timeout (60s)

### ISSUE THREAD

**Issue by ronott** [petitssuisses/piwigo-ShareAlbum#86]
Hi there,

When trying to share a private album, the plugin runs into a "PHP max execution time exceeded" timeout.

`Fatal error: Maximum execution time of 60 seconds exceeded in /path/to/plugins/ShareAlbum/include/sharealbum_functions.inc.php on line 105`

The album I'm trying to share has no permalink, I've disabled all options in the Share Album Configuration except  "Hide menu for album visitors". The photos and album have the correct permissions set (as explained in issue “You are not authorized to access the requested page”).

Environment:
- Piwigo 12.1.0 
- Operating system: Linux
- PHP: 8.0.12 (Show info) [2021-11-14 11:09:12]
- MySQL: 5.5.5-10.3.31-MariaDB [2021-11-14 11:09:12]
- Graphics Library: ImageMagick 7.1.0-10

Activated Plugins:
- AStat.2
- Automatic Size
- Copyrights
- Download Permissions
- Exiftool Keywords
- Extended Description
- External Reference
- Force HTTPS
- Grum Plugins Classes.3
- GThumb+
- LocalFiles Editor
- ShareAlbum
- SmartAlbums

If you need anymore information, tell me and I'll try to get it ;)

**Comment by ronott** [comment]
Seems PHP 8.0 is the culprit ... when switching to PHP 7.4, Share Album works like a charm.

**Comment by kisjuhos** [comment]
Fix line 236 from:
`$new_user_id = sharealbum_register_user($sharealbum_new_user,sharealbum_generate_code(SHAREALBUM_USER_PASSWORD_LENGTH, false,true));`
to:
`$new_user_id = sharealbum_register_user($sharealbum_new_user,SHAREALBUM_USER_PASSWORD_LENGTH);`

**Comment by petitssuisses** [comment]
Thanks for the issue sharting, that was it. This one is fixed thanks to latest commit. Updated 12.3 version is available on Piwigo.org.
