### ISSUE TITLE
Thumbnails list not showing on frontend

### ISSUE THREAD

**Issue by Thanatermesis** [petitssuisses/piwigo-ShareAlbum#87]
The album shows all the images / thumbnails in normal mode in the frontend, when switching to Private they still show up. But when using the Share link for some reason it shows only the first photo

**Comment by petitssuisses** [comment]
If you go to the pictures pages in Piwigo you can see the rights for photos visibility. 
Any difference between the first and the others ? Pictures must have "Everybody" in the "Who can see this photo" to be displayed when shared through a Private Album

**Comment by Thanatermesis** [comment]
Yes the photos are set to everybody;
- when album is public, all the photos are shown
- when album is private, all the photos are shown
- when using with "share link" to an anonymous user/session (incognito for example), it shows only the first photo
