### ISSUE TITLE
Deprecated: Required parameter $user_id follows optional parameter $nb_image_page

### ISSUE THREAD

**Issue by SanoKriss** [petitssuisses/piwigo-ShareAlbum#91]
PHP 8.0.12
`Deprecated: Required parameter $user_id follows optional parameter $nb_image_page in C:\xampp\htdocs\piwigo\plugins\ShareAlbum\include\sharealbum_functions.inc.php on line 327`

**Comment by tanty** [comment]
I'm having the same error:

```
Deprecated
: Required parameter $user_id follows optional parameter $nb_image_page in
/gallery/plugins/ShareAlbum/include/sharealbum_functions.inc.php
on line
327
```

I using linuxserver's container:

https://docs.linuxserver.io/images/docker-piwigo

```
# /usr/bin/php --version
PHP 8.0.25 (cli) (built: Oct 26 2022 12:04:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.25, Copyright (c) Zend Technologies
```

Piwigo 13.2.0 and ShareAlbum 12.3

**Comment by tanty** [comment]
Probably #92 is a duplicate of this.

**Comment by petitssuisses** [comment]
Hi, thanks for reporting. Just fixed, will be released with the new update. 
It was effectively a PHP 8 deprecation
