### ISSUE TITLE
ShareAlbum doesnt work under PHP 8.0

### ISSUE THREAD

**Issue by francwalter** [petitssuisses/piwigo-ShareAlbum#92]
Hallo
I have Piwigo 13.1.0 on my Ubuntu 18.04 LTS with PHP 8.0.25
I just switched to PHP 8.0 as PHP 7.4 is EOL this month but now I noticed that ShareAlbum 12.3 gives me Warnings and doesnt work:
ShareAlbum > Shared Albums:

```
Warning: Undefined array key "INTRO_CONTENT" in /var/www/example.org/gallery/piwigo/_data/templates_c/p6jhns^d31bf4395de7865471a149f436283ddfb456ba83_0.file.albums.tpl.php on line 60

Warning: Attempt to read property "value" on null in /var/www/example.org/gallery/piwigo/_data/templates_c/p6jhns^d31bf4395de7865471a149f436283ddfb456ba83_0.file.albums.tpl.php on line 60
```

and below this:

```
Verknüpfungen anzeigen : Warning: Undefined array key "show_link" in /var/www/example.org/gallery/piwigo/_data/templates_c/p6jhns^d31bf4395de7865471a149f436283ddfb456ba83_0.file.albums.tpl.php on line 129
> Ja Warning: Undefined array key "show_link" in /var/www/example.org/gallery/piwigo/_data/templates_c/p6jhns^d31bf4395de7865471a149f436283ddfb456ba83_0.file.albums.tpl.php on line 130
checked="checked" value="no"> Nein - Sortieren nach : 
```

I did a reset of the Plugin (strange: the first press of reset gives an error, the second says success, again press gives error etc.).
I installed clean and new Piwigo 13.1 and installed only AlbumShare, now I have the same errors plus the Warning:

`Deprecated: Required parameter $user_id follows optional parameter $nb_image_page in /var/www/example.org/piwigo/plugins/ShareAlbum/include/sharealbum_functions.inc.php on line 327`

I fixed this before already (one fix in the declaration and two fixes when the function is called). I could do at least for this warning a PR if interest present, but I fear this repo could be abandoned, no answer yet, then I wont do the work in vain.

Is ShareAlbum not fit for PHP 8 yet?
Thank, frank

**Comment by petitssuisses** [comment]
Hallo
Thanks for your feedback. All of this has been solved, I will commit and release the new version
Arnaud
