### ISSUE TITLE
Share URL adding undesired Port by default

### ISSUE THREAD

**Issue by HStep20** [petitssuisses/piwigo-ShareAlbum#98]
Each time I go to share an album, Ive noticed that the generated url seems to include a port mapping (`:80`) in the default URL it creates. For example, my latest album created this url - `https://pics.mydomain.net:80/?xauth=znjxbfklzHEjE`.

While its easy to cut those three characters out of the URL, it is a bit inconvenient to do it every time I send the URL somewhere. Is there a setting within the plugins Config files that will stop it from adding the Port Mapping to the URL? None of the available settings in the UI seem to disable that creation of a port when sharing an album.

**Comment by petitssuisses** [comment]
Are you behind a reverse proxy ?

**Comment by HStep20** [comment]
Yep - I thought I had mentioned that in the issue, but I have it proxied with NginxProxyManager. No additional config or headers set up within nginx

**Comment by HStep20** [comment]
After some testing (since I noticed photo loading and the mobile app were broken as well), it seemed to be an issue with my proxy. While Piwigo 14 seems to bring a new config option which will hopefully help resolve the issue for some, I ended up editing the Advanced Config on my NginxProxyManager entry with the following that fixed it:

```
location / {
    proxy_pass http://$server:$port;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host photos.yourdomain.com;
}
```
